### ISSUE TITLE
How should <ci> type attributes be handled?

### ISSUE THREAD

**Issue by christianp** [mathjax/ctop#33]
The spec for `<ci>` - http://www.w3.org/TR/MathML3/chapter4.html#contm.ci - lists a few types. Some of these should result in different renderings, for example "vector" and "matrix". What should those be?

**Comment by davidcarlisle** [comment]
On 25 April 2014 14:16, Christian Perfect notifications@github.com wrote:

> The spec for <ci> - http://www.w3.org/TR/MathML3/chapter4.html#contm.ci -
> lists a few types. Some of these should result in different renderings, for
> example "vector" and "matrix". What should those be?
> 
> —

I think you could justify doing nothing (what the xsl does) using bold
italic (for single letters that would otherwise be italic) or using bold
upright. Conventions for vectors seem to regularly generate heat on TeX
fora as to what the correct display is, not least as there are ISO
standards (which may be followed in engineering but widely not followed in
maths)

Pick one and stick to it:-)

http://tex.stackexchange.com/questions/144978/bold-italics-is-hard-to-distinguish-from-italics

One benefit that I'd hope eventually from doing this in JS rather than xslt
is that it becomes easier to customise this from within a normal mathjax
configuration script. I don't think that is essential first time round but
if the code uses a mathvariant-for-vectors string that defaults to
"bold-italic" then perhaps it should be easy for a page author to set that
to bold if they want upright vectors...

**Comment by christianp** [comment]
OK, I've got it so ctop.js reads from a dictionary called `CToP.cistyles` to see what style to apply. Page authors can change that to change the behaviour.
