### ISSUE TITLE
rendering lambda

### ISSUE THREAD

**Issue by christianp** [mathjax/ctop#5]
http://www.w3.org/Math/testsuite/build/main/Content/BasicContentElements/lambda/rec-lambda1-form.xhtml
http://www.w3.org/Math/testsuite/build/main/Content/BasicContentElements/lambda/rec-lambda2-form.xhtml

`lambda` has two suggestions in the spec. This one is valid but maybe we prefer the other?

**Comment by davidcarlisle** [comment]
On 11 April 2014 11:16, Christian Perfect notifications@github.com wrote:

> http://www.w3.org/Math/testsuite/build/main/Content/BasicContentElements/lambda/rec-lambda1-form.xhtml
> 
> http://www.w3.org/Math/testsuite/build/main/Content/BasicContentElements/lambda/rec-lambda2-form.xhtml
> 
> lambda has two suggestions in the spec. This one is valid but maybe we
> prefer the other?
> 
> ## 

Personally I think that if you have got as far as marking up a function as
<lambda> you'd probably want a lambda, but Robert always argued that
content mathml was aimed  (mostly) at high school level  and since lambda
calculus is quite often a post graduate kind of notation it wasn't
suitable. So there are two images in the spec...

I'm not sure if there will be possibilities for "easy" user customisation
of this kind of choice if you implement both? Otherwise just pick one, I
think either choice is justifiable.

David

**Comment by christianp** [comment]
Closing: if authors want a different presentation, they can use annotation-xml or override `CToP.tokens['lambda']`.
